### ISSUE TITLE
[ REWORK ] - Angular Page Redo

### ISSUE THREAD

**Issue by AleixFerre** [CatalaHD/Chrome-Extension#2]
Base on [this](https://www.youtube.com/watch?v=WqLPSZZ2dcs) design

![image](https://user-images.githubusercontent.com/12767963/161422654-ca8728d1-5250-498b-87e1-2da9ffa22371.png)

## TODO:

- [x] Fons de pantalla bonic de les estrelles o alguna cosa fancy lol
- [x] Que et mostri la hora que es i el dia que es
- [x] Que et mostri els bookmarks (CRUD)
- [x] Que et mostri el temps amb la weather api
